### ISSUE TITLE
CCL does not work in IDEA 8.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TristinDavis/codecompletionlive#4]
```
Try any completion and the following stacktrace is generated:

Could not initialize class
org.dubik.codecompletionlive.actions.CodeCompletionLiveActionExecutor
java.lang.NoClassDefFoundError: Could not initialize class
org.dubik.codecompletionlive.actions.CodeCompletionLiveActionExecutor
    at
org.dubik.codecompletionlive.actions.CodeCompletionLiveAction$1.run(CodeCompleti
onLiveAction.java:45)
    at
com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocat
or.java:27)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:35)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:99)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:217)
    at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269
)
    at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174
)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

Original issue reported on code.google.com by `haxthepl...@gmail.com` on 17 Nov 2008 at 1:28
